apiVersion: v1
kind: Pod
metadata:
  namespace: ai-ems-dev
  labels:
    test: health-check
  name: mysql
...
spec:
  containers:
  - name: mysql
    args:
    image: mysql:5.7
    livenessProbe: 
      exec: 
        command: 
        - /bin/bash
        - '-c'
        - timeout 60 /opt/eap/bin/livenessProbe.sh
      periodSeconds: 10 
      successThreshold: 1 
      failureThreshold: 3 
      
...

kind: Deployment
apiVersion: apps/v1
...
spec:
...
  template:
    spec:
      containers:
        - resources: {}
          readinessProbe: 
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ruby-ex
          livenessProbe: 
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
