apiVersion: v1
kind: Pod
metadata:
  labels:
    test: health-check
  name: my-application
...
spec:
  containers:
  - name: goproxy-app 
    args:
    image: k8s.gcr.io/goproxy:0.1 
    readinessProbe: 
      exec: 
        command: 
        - cat
        - /tmp/healthy
...

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: health-check
  name: my-application
...
spec:
  containers:
  - name: goproxy-app 
    args:
    image: k8s.gcr.io/goproxy:0.1 
    livenessProbe: 
      httpGet: 
        scheme: HTTPS 
        path: /healthz
        port: 8080 
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
    startupProbe: 
      httpGet: 
        path: /healthz
        port: 8080 
      failureThreshold: 30 
      periodSeconds: 10 

...

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: health-check
  name: my-application
...
spec:
  containers:
  - name: goproxy-app 
    args:
    image: k8s.gcr.io/goproxy:0.1 
    livenessProbe: 
      exec: 
        command: 
        - /bin/bash
        - '-c'
        - timeout 60 /opt/eap/bin/livenessProbe.sh
      periodSeconds: 10 
      successThreshold: 1 
      failureThreshold: 3 
      
...

kind: Deployment
apiVersion: apps/v1
...
spec:
...
  template:
    spec:
      containers:
        - resources: {}
          readinessProbe: 
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ruby-ex
          livenessProbe: 
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
...

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: health-check
  name: my-application
spec:
  containers:
  - name: my-container 
    args:
    image: k8s.gcr.io/goproxy:0.1 
    livenessProbe: 
      tcpSocket:  
        port: 8080 
      initialDelaySeconds: 15 
      periodSeconds: 20 
      timeoutSeconds: 10 
    readinessProbe: 
      httpGet: 
        host: my-host 
        scheme: HTTPS 
        path: /healthz
        port: 8080 
    startupProbe: 
      exec: 
        command: 
        - cat
        - /tmp/healthy
      failureThreshold: 30 
      periodSeconds: 20 
      timeoutSeconds: 10 
      
