apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: ai-ems-dev
type: opaque
stringData:
  MYSQL_USER_PASSWORD: admin
  MYSQL_ROOT_PASSWORD: pasmsQlaiems

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ai-ems-dev
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
  namespace: ai-ems-dev
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      namespace: ai-ems-dev
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
      namespace: ai-ems-dev
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi
