apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: opaque
stringData:
  MYSQL_USER: root
  MYSQL_PASSWORD: pasmsQlaiems

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_USER
          value: "mysql-pass"
        - name: MYSQL_PASSWORD
          value: "mysql-pass"
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi
